// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6c_MAAMRJ1XkjvMEW3d_UXrQq_Vit5Co',
    appId: '1:1049172139596:web:ace5f98afd7f320f58dee9',
    messagingSenderId: '1049172139596',
    projectId: 'streamingdjlive-2fd7d',
    authDomain: 'streamingdjlive-2fd7d.firebaseapp.com',
    storageBucket: 'streamingdjlive-2fd7d.firebasestorage.app',
    measurementId: 'G-188GE3T6X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUjh-f4OY3mLiAer8gUsk0aZ-C1AsQrgk',
    appId: '1:1049172139596:android:f052162f7e5f5a1058dee9',
    messagingSenderId: '1049172139596',
    projectId: 'streamingdjlive-2fd7d',
    storageBucket: 'streamingdjlive-2fd7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr-JvjYVZ3Zgf6nNV_6BrsLs1efBsdWqM',
    appId: '1:1049172139596:ios:4246fef106589da458dee9',
    messagingSenderId: '1049172139596',
    projectId: 'streamingdjlive-2fd7d',
    storageBucket: 'streamingdjlive-2fd7d.firebasestorage.app',
    iosBundleId: 'com.example.streamingDjlive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr-JvjYVZ3Zgf6nNV_6BrsLs1efBsdWqM',
    appId: '1:1049172139596:ios:4246fef106589da458dee9',
    messagingSenderId: '1049172139596',
    projectId: 'streamingdjlive-2fd7d',
    storageBucket: 'streamingdjlive-2fd7d.firebasestorage.app',
    iosBundleId: 'com.example.streamingDjlive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6c_MAAMRJ1XkjvMEW3d_UXrQq_Vit5Co',
    appId: '1:1049172139596:web:263afdef72999c7e58dee9',
    messagingSenderId: '1049172139596',
    projectId: 'streamingdjlive-2fd7d',
    authDomain: 'streamingdjlive-2fd7d.firebaseapp.com',
    storageBucket: 'streamingdjlive-2fd7d.firebasestorage.app',
    measurementId: 'G-WGJF5SL07K',
  );
}
